name: CI

on:
  push:
    branches: [ master, develop, workbench-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/v20.06.14.107/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        ros config set dynamic-space-size 2048

        ros install lem
        ros install cxxxr/sblint
        ros install fukamachi/rove/reduce-macro-expansion
        export PATH=$HOME/.roswell/bin:$PATH
        ros -v -s lem-tests

        sblint lib/base/lem-base.asd
        sblint lib/core/lem-core.asd
        sblint lib/lisp-syntax/lem-lisp-syntax.asd
        sblint modes/lisp-mode/lem-lisp-mode.asd
